### ISSUE TITLE
As a media fabricator we need an hardware package for the computer, projector, internet, and power so that it's easy to install anywhere in the museum

### ISSUE THREAD

**Issue by bryankennedy** [scimusmn/stranger-science-game#13]

**Comment by bryankennedy** [comment]
Issues here:
 - Running power to the projector, computer setup can be difficult and a trip hazard.
 - We might want to find a computer that can get installed with the projector in the grid.

**Comment by bryankennedy** [comment]
The display computer needs to have enough graphic capabilities to push the game display.

**Comment by tnordberg** [comment]
This issue was moved to scimusmn/multiplayer-phone-game#12
